plugins {
    id 'com.android.application'
}

android {
    namespace 'com.zeusstudio'
    compileSdk 36

    defaultConfig {
        applicationId 'com.zeusstudio'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '0.1.0'

        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main {
            jniLibs.srcDirs 'libnode/bin'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
}